# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib, php, phpPackages, unzip, stdenv, runCommandLocal, writeText, fetchurl

# Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let

  composerPath = phpPackages.composer.src;
  cacheEntries = [
    { name = "aura_sql-5.0.2.0"; filename = "aura/sql/f20d5be16c24848bd73908f9aca2e0b6272e46f2.zip"; sha256 = "cbc999ae3b7f91aada0b4c8d8a950fc23023c22e3176903c74e38cea69190670"; urls = [ "https://api.github.com/repos/auraphp/Aura.Sql/zipball/0e1fdc674e2a11b4ab83286c4410426714ece1e1" ]; }
    { name = "guzzlehttp_guzzle-7.8.1.0"; filename = "guzzlehttp/guzzle/e28c3b7e52d87e7c00770dcc99ab1f22e096aa4c.zip"; sha256 = "5b776e5d7f5a9da40f0b198f6e5b1311c6e53c50c08ab4af02731624d484902b"; urls = [ "https://api.github.com/repos/guzzle/guzzle/zipball/41042bc7ab002487b876a0683fc8dce04ddce104" ]; }
    { name = "guzzlehttp_promises-2.0.2.0"; filename = "guzzlehttp/promises/6487c9267c559544f801e1405c31b54816e2292b.zip"; sha256 = "ae9096dc5fe13f14f99f690267455b70ef66cf788aa23f218b74301482cf0bdc"; urls = [ "https://api.github.com/repos/guzzle/promises/zipball/bbff78d96034045e58e13dedd6ad91b5d1253223" ]; }
    { name = "guzzlehttp_psr7-2.6.2.0"; filename = "guzzlehttp/psr7/868a4a002e06bdaa09164524df71587097d61304.zip"; sha256 = "b5d57791438ba8e8dd076c5e5d6e913c5508e4286ebd94610ed8b47eddbfc04c"; urls = [ "https://api.github.com/repos/guzzle/psr7/zipball/45b30f99ac27b5ca93cb4831afe16285f57b8221" ]; }
    { name = "laminas_laminas-diactoros-2.26.0.0"; filename = "laminas/laminas-diactoros/b42c94d8dd8ace7095aefd0584208a96fd355e2c.zip"; sha256 = "f13b5930eba6dfc5ecafb8f183cf5b22c3ef917814d19677d0d9b55bfcaba328"; urls = [ "https://api.github.com/repos/laminas/laminas-diactoros/zipball/6584d44eb8e477e89d453313b858daac6183cddc" ]; }
    { name = "league_mime-type-detection-1.14.0.0"; filename = "league/mime-type-detection/62c40126e5de1cfea8ce038556d6b71bee4bbb4a.zip"; sha256 = "f2791a0d84571f58edbbe3f404ad8913567c339d61c7880e2dcb5fc09282582f"; urls = [ "https://api.github.com/repos/thephpleague/mime-type-detection/zipball/b6a5854368533df0295c5761a0253656a2e52d9e" ]; }
    { name = "nyholm_psr7-1.8.1.0"; filename = "nyholm/psr7/52aa4d3aa21e26a42cadaa8a9d7cb1a33ee052a6.zip"; sha256 = "8f1e81af91e9c9e2de490ebaf14e824bcf800ddb44473cc3614d66668fd72903"; urls = [ "https://api.github.com/repos/Nyholm/psr7/zipball/aa5fc277a4f5508013d571341ade0c3886d4d00e" ]; }
    { name = "nyholm_psr7-server-1.1.0.0"; filename = "nyholm/psr7-server/5aa0a006606add64ffd15f1780a40600adb6f129.zip"; sha256 = "4e9139e34857344bd33fcfa9c4812f02c2fc6e367ab6e0e1a020275c5690affc"; urls = [ "https://api.github.com/repos/Nyholm/psr7-server/zipball/4335801d851f554ca43fa6e7d2602141538854dc" ]; }
    { name = "psr_container-2.0.2.0"; filename = "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip"; sha256 = "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"; urls = [ "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963" ]; }
    { name = "psr_http-client-1.0.3.0"; filename = "psr/http-client/8a0eb9bbf4ceddbff9fd328c582c07269c8888ab.zip"; sha256 = "5d3fc583e721d451a0cc2073680476236199cd1680a0d9da1756e8152496deb5"; urls = [ "https://api.github.com/repos/php-fig/http-client/zipball/bb5906edc1c324c9a05aa0873d40117941e5fa90" ]; }
    { name = "psr_http-factory-1.0.2.0"; filename = "psr/http-factory/d8875dced84085f47fee02b6c9a8c288d7ae271f.zip"; sha256 = "a8cff2adbd84c58c0fe02ed401026c7364c893670352d025f88e060087adf1ef"; urls = [ "https://api.github.com/repos/php-fig/http-factory/zipball/e616d01114759c4c489f93b099585439f795fe35" ]; }
    { name = "psr_http-message-1.1.0.0"; filename = "psr/http-message/9724356cb916f33cc47fb6738873b81e36cee3bf.zip"; sha256 = "10a0ba4904056813e7c176694dd41e26aa2b72dca0438f23038376dda5d207e9"; urls = [ "https://api.github.com/repos/php-fig/http-message/zipball/cb6ce4845ce34a8ad9e68117c10ee90a29919eba" ]; }
    { name = "psr_http-server-handler-1.0.2.0"; filename = "psr/http-server-handler/58f37cf292f35803247f45c05adf714dfb58be95.zip"; sha256 = "b4e05ba08e4a03f66b4a94936bf0a4f8f885f69bfe64d770a0c867d64340aa31"; urls = [ "https://api.github.com/repos/php-fig/http-server-handler/zipball/84c4fb66179be4caaf8e97bd239203245302e7d4" ]; }
    { name = "psr_http-server-middleware-1.0.2.0"; filename = "psr/http-server-middleware/7a11eac8da5d553694fdb7996b1a4c1842d1b720.zip"; sha256 = "4bc24a30f219b1eb46f8f175fe27e125cf8b029d4ce3e6c4f34b2429c6877b82"; urls = [ "https://api.github.com/repos/php-fig/http-server-middleware/zipball/c1481f747daaa6a0782775cd6a8c26a1bf4a3829" ]; }
    { name = "psr_log-3.0.0.0"; filename = "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip"; sha256 = "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"; urls = [ "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001" ]; }
    { name = "ralouphie_getallheaders-3.0.3.0"; filename = "ralouphie/getallheaders/ddc5f4c7ab3d868f5060717336a0d93475d53175.zip"; sha256 = "ef0165da5690da666ab4cb88bb4cec0d50372e3e7c922532c5795a3567b367af"; urls = [ "https://api.github.com/repos/ralouphie/getallheaders/zipball/120b605dfeb996808c31b6477290a714d356e822" ]; }
    { name = "symfony_console-6.4.1.0"; filename = "symfony/console/120df30ebae29ea0243e993c38c5385468ae0b6a.zip"; sha256 = "a199f70bff84d3b284f91b1743622ac6801f4b9bd59aa706c32ace9890b44d3b"; urls = [ "https://api.github.com/repos/symfony/console/zipball/a550a7c99daeedef3f9d23fb82e3531525ff11fd" ]; }
    { name = "symfony_deprecation-contracts-3.4.0.0"; filename = "symfony/deprecation-contracts/3a056d55414a97879a7988336ee8da233ff344ba.zip"; sha256 = "a986294f5e57bff601dd9af7b28b8dfa488c0d7f28266fc05a014b2e48120c5c"; urls = [ "https://api.github.com/repos/symfony/deprecation-contracts/zipball/7c3aff79d10325257a001fcf92d991f24fc967cf" ]; }
    { name = "symfony_polyfill-ctype-1.28.0.0"; filename = "symfony/polyfill-ctype/d699d9cb7d3d258b5802c923ee1dd236a79cff09.zip"; sha256 = "a362b81b307d71fce861ef27ebcba1c874f739973686a56043842c38e8cdd37a"; urls = [ "https://api.github.com/repos/symfony/polyfill-ctype/zipball/ea208ce43cbb04af6867b4fdddb1bdbf84cc28cb" ]; }
    { name = "symfony_polyfill-intl-grapheme-1.28.0.0"; filename = "symfony/polyfill-intl-grapheme/aa41147fac08567abb7e6eb5a881c2dab79e3818.zip"; sha256 = "11b4082c2bc12fb91d48a919800bf9dac726be91900a164c3cb8887217c348a6"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/875e90aeea2777b6f135677f618529449334a612" ]; }
    { name = "symfony_polyfill-intl-normalizer-1.28.0.0"; filename = "symfony/polyfill-intl-normalizer/d8618cf8f62db9f645b07ef2ac3c3e32fac2dc2d.zip"; sha256 = "d09ec813416ae02cd41d590fd0bd47c3f6b002dea9977d08ece40411a3804a57"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92" ]; }
    { name = "symfony_polyfill-mbstring-1.28.0.0"; filename = "symfony/polyfill-mbstring/f1445f434ecaa75181b92e7950b8cb6c1f5ab170.zip"; sha256 = "8a5b4944726b1728e62f48467bd4e5c8fff1c1cc32d4e13f88a3450abc0874d4"; urls = [ "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/42292d99c55abe617799667f454222c54c60e229" ]; }
    { name = "symfony_serializer-6.4.1.0"; filename = "symfony/serializer/a91285a4c18af678c6c4a44ced5236325c5956a9.zip"; sha256 = "8c91f533d8abd1d9a474f7649e464687909f6b7285c489ca0e20dd74f20d0321"; urls = [ "https://api.github.com/repos/symfony/serializer/zipball/7ead272e62c9567df619ef3c49809bf934ddbc1f" ]; }
    { name = "symfony_service-contracts-3.4.0.0"; filename = "symfony/service-contracts/d68b127dc9fc821a0fab496d514756a4ee07fdf7.zip"; sha256 = "9358a30cfcdc2091aabe596b6fb335b66dba155324b58d79a09e40eada7797ae"; urls = [ "https://api.github.com/repos/symfony/service-contracts/zipball/b3313c2dbffaf71c8de2934e2ea56ed2291a3838" ]; }
    { name = "symfony_string-7.0.0.0"; filename = "symfony/string/9caf05e3b5d456f4a6b3a5a840680aec4263af23.zip"; sha256 = "c5ceded6597fe5433d11708b7fd6a4729b82aa4123f350216fcf8b3397bd3d0a"; urls = [ "https://api.github.com/repos/symfony/string/zipball/92bd2bfbba476d4a1838e5e12168bef2fd1e6620" ]; }
    { name = "tuupola_base62-2.1.0.0"; filename = "tuupola/base62/e044fecd8fbee6caf3d021964a6c9f2bae9e99f0.zip"; sha256 = "8e3fa8b815155c73d3bdd00f43bcb838ee35685bb3472e891d6b9c3ded2fe966"; urls = [ "https://api.github.com/repos/tuupola/base62/zipball/7406145a9cf8c567cd35ad7358d1b24828cbcfdb" ]; }
    { name = "webonyx_graphql-php-14.11.10.0"; filename = "webonyx/graphql-php/ebf003b9a76f4304dedb85d1a57cd6efec91a6b9.zip"; sha256 = "2bb2b6f3ab1ecd78e057b060d87970a4f3c9661db85ce8a8256e325247deeb6b"; urls = [ "https://api.github.com/repos/webonyx/graphql-php/zipball/d9c2fdebc6aa01d831bc2969da00e8588cffef19" ]; }
    { name = "doctrine_instantiator-2.0.0.0"; filename = "doctrine/instantiator/48cd70ce44111f1be53796d18d263cd47da09a3f.zip"; sha256 = "966dccf8ebce17e2883e59d65c4172a3c4008d2c0039421523a2823f0e872a15"; urls = [ "https://api.github.com/repos/doctrine/instantiator/zipball/c6222283fa3f4ac679f8b9ced9a4e23f163e80d0" ]; }
    { name = "myclabs_deep-copy-1.11.1.0"; filename = "myclabs/deep-copy/938b4d6e032f3a3c3ff9a0a2d69966e7209ae50c.zip"; sha256 = "b2f08625012b095f143ec11a26e055d9d3ba3b2aa1d4ae571a24b3459227649a"; urls = [ "https://api.github.com/repos/myclabs/DeepCopy/zipball/7284c22080590fb39f2ffa3e9057f10a4ddd0e0c" ]; }
    { name = "nikic_php-parser-4.17.1.0"; filename = "nikic/php-parser/f18b4b4ae6dccc1e5d3c4ef451a8d32a06f14194.zip"; sha256 = "3ec01f98b727ca79fb1b59de90ba0a0cd5daf32baad7c066b1fdb1fdbe33aa28"; urls = [ "https://api.github.com/repos/nikic/PHP-Parser/zipball/a6303e50c90c355c7eeee2c4a8b27fe8dc8fef1d" ]; }
    { name = "phar-io_manifest-2.0.3.0"; filename = "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip"; sha256 = "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"; urls = [ "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53" ]; }
    { name = "phar-io_version-3.2.1.0"; filename = "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip"; sha256 = "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"; urls = [ "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74" ]; }
    { name = "phpunit_php-code-coverage-9.2.29.0"; filename = "phpunit/php-code-coverage/0cc48ee02b58216e59f8de1a1ab3ae8213f86fb6.zip"; sha256 = "e8f9b9d6d7a9b67ded909da49337b3b2ac60a7fd497dc84075b2f56d6d5f01ae"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/6a3a87ac2bbe33b25042753df8195ba4aa534c76" ]; }
    { name = "phpunit_php-file-iterator-3.0.6.0"; filename = "phpunit/php-file-iterator/4fd4ef934d9b090aff1c14e5987f251c5d6b2d0c.zip"; sha256 = "d9b2fe0929a3a844490dd9d32dbbd09a19713e3356e0199b26bc0c181c6a0790"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf" ]; }
    { name = "phpunit_php-invoker-3.1.1.0"; filename = "phpunit/php-invoker/18d90380b8ff6f566265ca070b4bcfe4c4bbd34c.zip"; sha256 = "d091fc2206ce86ff8664068b04952c8d8ff6dc12b7d864c1a8bf92c4adb416ef"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-invoker/zipball/5a10147d0aaf65b58940a0b72f71c9ac0423cc67" ]; }
    { name = "phpunit_php-text-template-2.0.4.0"; filename = "phpunit/php-text-template/b8d58f7d3789d6fd84cb6a82ebcb5776ab609787.zip"; sha256 = "98a2b504e34e4b99e433f6d738b877d5847ea9b2800f7d8534f147eebf3fc839"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28" ]; }
    { name = "phpunit_php-timer-5.0.3.0"; filename = "phpunit/php-timer/b71ded866a460bbdb922b5eb818f4ed163f38f0c.zip"; sha256 = "cacc8ec54d593bfaa1627bc67e110b0ef9d2f1d2ae98007d8b2bcc4fbc3f2f3c"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2" ]; }
    { name = "phpunit_phpunit-9.6.15.0"; filename = "phpunit/phpunit/451ee6a6f6e99a9021783d60c368e269e42dfd7a.zip"; sha256 = "9352f4db48ea937ac7938fc3882230cf53f56f8b061564abec0bdd0eaf814780"; urls = [ "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/05017b80304e0eb3f31d90194a563fd53a6021f1" ]; }
    { name = "roave_security-advisories-dev-master"; filename = "roave/security-advisories/0c580f7f9fcd17631248a23338ccf75576408eb4.zip"; sha256 = "eb7c462fced8c41e613f7e5ef8339f8496af87215591ba5477690ef4017e5ad0"; urls = [ "https://api.github.com/repos/Roave/SecurityAdvisories/zipball/b4728d9c4af8c60b059c1d7872759eedacccdb12" ]; }
    { name = "sebastian_cli-parser-1.0.1.0"; filename = "sebastian/cli-parser/f4b297cc8d9ba3ba47f6d1c84b9d69bac882a7b1.zip"; sha256 = "6740017ab612481526b458876d8a9aba23326099ca0e0cb7263dcd1470fb981c"; urls = [ "https://api.github.com/repos/sebastianbergmann/cli-parser/zipball/442e7c7e687e42adc03470c7b668bc4b2402c0b2" ]; }
    { name = "sebastian_code-unit-1.0.8.0"; filename = "sebastian/code-unit/2175508c3a7c4f57c236668e95692cb4f230ef7e.zip"; sha256 = "f51e89b8ecce2a310a2cef0d7e8256378540fe1da91daa7a25a5e50c0ae87413"; urls = [ "https://api.github.com/repos/sebastianbergmann/code-unit/zipball/1fc9f64c0927627ef78ba436c9b17d967e68e120" ]; }
    { name = "sebastian_code-unit-reverse-lookup-2.0.3.0"; filename = "sebastian/code-unit-reverse-lookup/68fb878dfd88a53caa52899dcad6f00ede9925b2.zip"; sha256 = "4a6a9beb03ba89c65df74e0200eef997aed640f362a94a224e61aa3ffe5f32c0"; urls = [ "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5" ]; }
    { name = "sebastian_comparator-4.0.8.0"; filename = "sebastian/comparator/6a8576886b5e1cfd55783584d8a948ab21adc37c.zip"; sha256 = "7ca0bc15be7811ff9964e059889466bab579a93f7ed34cd02e58f0aef85c1155"; urls = [ "https://api.github.com/repos/sebastianbergmann/comparator/zipball/fa0f136dd2334583309d32b62544682ee972b51a" ]; }
    { name = "sebastian_complexity-2.0.2.0"; filename = "sebastian/complexity/76ac0bc95bb26576a1588ac4917fe13f3107573f.zip"; sha256 = "ce23bcd6c0fe24007e0ad6bf3cc17fa7beedf11dfdc6e46c84eb6b882cfa9ef8"; urls = [ "https://api.github.com/repos/sebastianbergmann/complexity/zipball/739b35e53379900cc9ac327b2147867b8b6efd88" ]; }
    { name = "sebastian_diff-4.0.5.0"; filename = "sebastian/diff/dc3b4abbb26806e34efa7c58a98cf0b30f12e3e9.zip"; sha256 = "a0ca8ac40022943cee898fb8e0035268e3f76c136c0d5d9dab93a2b8c2212039"; urls = [ "https://api.github.com/repos/sebastianbergmann/diff/zipball/74be17022044ebaaecfdf0c5cd504fc9cd5a7131" ]; }
    { name = "sebastian_environment-5.1.5.0"; filename = "sebastian/environment/2233d3b38ac6d485959f6c153c851f07547fee65.zip"; sha256 = "f653465ac3278f2109df985a8cfab6bb8a0524f4f0861d4e993f001b872d0408"; urls = [ "https://api.github.com/repos/sebastianbergmann/environment/zipball/830c43a844f1f8d5b7a1f6d6076b784454d8b7ed" ]; }
    { name = "sebastian_exporter-4.0.5.0"; filename = "sebastian/exporter/d097047a341fb0e411c70e540a62a9ca3af9479c.zip"; sha256 = "d290d6d4c1ed86927a833cc9cceb9fefb4b55d6cda7774e38b43f28c3692dea8"; urls = [ "https://api.github.com/repos/sebastianbergmann/exporter/zipball/ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d" ]; }
    { name = "sebastian_global-state-5.0.6.0"; filename = "sebastian/global-state/a9faa0f62283cda18690c5c4ea818c631c3f386d.zip"; sha256 = "7c290ffa27754a162afb8c7d6eaea5365ec049ca0d552b3ea912a89af7826952"; urls = [ "https://api.github.com/repos/sebastianbergmann/global-state/zipball/bde739e7565280bda77be70044ac1047bc007e34" ]; }
    { name = "sebastian_lines-of-code-1.0.3.0"; filename = "sebastian/lines-of-code/c83c674fbb96cf1b9525472250a2ec5c8e7784d6.zip"; sha256 = "60ae97d500e9d96e826afb01b5789c511fdb7fe6304a7c325fcf84ca8a4e5e39"; urls = [ "https://api.github.com/repos/sebastianbergmann/lines-of-code/zipball/c1c2e997aa3146983ed888ad08b15470a2e22ecc" ]; }
    { name = "sebastian_object-enumerator-4.0.4.0"; filename = "sebastian/object-enumerator/da625947c9c4e28182677035866359692138e8aa.zip"; sha256 = "c132dcacda3e4e0967aeabf068fa83f3f492a351c34bcd8f5101227ec01f0585"; urls = [ "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/5c9eeac41b290a3712d88851518825ad78f45c71" ]; }
    { name = "sebastian_object-reflector-2.0.4.0"; filename = "sebastian/object-reflector/89595d8936651649889c35a91221207e12331fda.zip"; sha256 = "4f673297cc7e85c41c8658c202e01ead4adae48d6c870ec070941bcfb50bb53c"; urls = [ "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/b4f479ebdbf63ac605d183ece17d8d7fe49c15c7" ]; }
    { name = "sebastian_recursion-context-4.0.5.0"; filename = "sebastian/recursion-context/4b7cea85c6a1d0a92ff75035f6b0545625890a5f.zip"; sha256 = "8102972caec5c2041cb1b156913ac9a320cca9943dc94cde79be43e7baf6e6a9"; urls = [ "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/e75bd0f07204fec2a0af9b0f3cfe97d05f92efc1" ]; }
    { name = "sebastian_resource-operations-3.0.3.0"; filename = "sebastian/resource-operations/c70bff160e611fd40d5d68d1f06d580b9496fb3a.zip"; sha256 = "d92f4b5b50d5e264d3b00ab31a3b80c0718f2689a1f3f23d101ce67a6e46ba5c"; urls = [ "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8" ]; }
    { name = "sebastian_type-3.2.1.0"; filename = "sebastian/type/6c52c952769f461058a7bcc9db2baadd3633dfc8.zip"; sha256 = "8507e504e5e67b8ac937a96373d980464fd8c1fa7211dd3f14fe2e2cccda6e2f"; urls = [ "https://api.github.com/repos/sebastianbergmann/type/zipball/75e2c2a32f5e0b3aef905b9ed0b179b953b3d7c7" ]; }
    { name = "sebastian_version-3.0.2.0"; filename = "sebastian/version/85e202da271e8389420827021d6c4f00bdd90951.zip"; sha256 = "e1c5424e05207360f511745290144dcad1df69f1789fd97eb0d1819a145f47af"; urls = [ "https://api.github.com/repos/sebastianbergmann/version/zipball/c6c1022351a901512170118436c764e473f6de8c" ]; }
    { name = "stephank_composer-plugin-nixify-1.1.0.0"; filename = "stephank/composer-plugin-nixify/6b00aedf28221acbb64a87222a0eb819404901f2.zip"; sha256 = "ac7cc480698f8717fb9fce4077b81303d37fe6ab2b89c8547cd7f9451598ee1e"; urls = [ "https://api.github.com/repos/stephank/composer-plugin-nixify/zipball/d93c4348388d714d7d81b41e34ccb2ae9c2131c2" ]; }
    { name = "symplify_monorepo-builder-11.2.20.0"; filename = "symplify/monorepo-builder/3d45aa588d1cd48e93d6a444743e173e1aff3de8.zip"; sha256 = "6e7726542db5a35c6948db83f6d5a71b4ba4569ace94d9062c814b81f4a7ce18"; urls = [ "https://api.github.com/repos/symplify/monorepo-builder/zipball/444efe08701776cb1a03b9f3600e715697519aa6" ]; }
    { name = "theseer_tokenizer-1.2.2.0"; filename = "theseer/tokenizer/229e106909831139bdfab1e27edd408d50fcc455.zip"; sha256 = "ebcda6cb34ca14e8b7c058b588e3e22e152e4b21f283eee2fa2d55247d40dc0f"; urls = [ "https://api.github.com/repos/theseer/tokenizer/zipball/b2ad5003ca10d4ee50a12da31de12a5774ba6b96" ]; }
  ];
  localPackages = [
  ];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings (args: ''
      (
        cacheFile=${escapeShellArg args.filename}
        cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
        mkdir -p "$(dirname "$cacheFilePath")"
        cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
      )
    '') cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings (args: ''
      sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
    '') localPackages
  );

in stdenv.mkDerivation {
  name = "meteia_meteia";
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
