# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib, php, phpPackages, unzip, stdenv, runCommandLocal, writeText, fetchurl

# Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let

  composerPath = phpPackages.composer.src;
  cacheEntries = [
    { name = "aura_sql-dev-psr-log-v3"; filename = "aura/sql/dd6a88b233bb7f87bb68c86cf3507c41806887fa.zip"; sha256 = "95fdfefba857723202f6b318d968af3216f5086573dceaf02a420285747f2406"; urls = [ "https://api.github.com/repos/jasonrm/Aura.Sql/zipball/c58ba7efeba12a4621facfa38cde30b8afcbd1f3" ]; }
    { name = "doctrine_inflector-2.0.4.0"; filename = "doctrine/inflector/c472576727cff1bbba07aada8d3a69de9254b92b.zip"; sha256 = "c72612500919c3f0ea8e76d7c4fbe7a1c79e43ff2f10109f0a359549e49203d1"; urls = [ "https://api.github.com/repos/doctrine/inflector/zipball/8b7ff3e4b7de6b2c84da85637b59fd2880ecaa89" ]; }
    { name = "laminas_laminas-diactoros-2.17.0.0"; filename = "laminas/laminas-diactoros/cf98ae7c3fe73ccbd23c3146e1cca895ff46c275.zip"; sha256 = "fa7b8c76f37d27b23b7b503681131ed2b25e8af9da4d2cf88854710ee8a3d50b"; urls = [ "https://api.github.com/repos/laminas/laminas-diactoros/zipball/5b32597aa46b83c8b85bb1cf9a6ed4fe7dd980c5" ]; }
    { name = "nyholm_psr7-1.5.1.0"; filename = "nyholm/psr7/5d6f09262bdbe7949bc2811cc73627ff51f389c1.zip"; sha256 = "9db56258c34bfd5a355a8196242a85f371252cbf2f7caf7f60b3a187032d1171"; urls = [ "https://api.github.com/repos/Nyholm/psr7/zipball/f734364e38a876a23be4d906a2a089e1315be18a" ]; }
    { name = "nyholm_psr7-server-1.0.2.0"; filename = "nyholm/psr7-server/fd3271e24f437b2fd91b74592dcdb152667fd079.zip"; sha256 = "206e92ebfcb8635b8ad6f460bdf5584b9dd7a139e18dd549b78c7d9e1582e600"; urls = [ "https://api.github.com/repos/Nyholm/psr7-server/zipball/b846a689844cef114e8079d8c80f0afd96745ae3" ]; }
    { name = "php-http_message-factory-1.0.2.0"; filename = "php-http/message-factory/3a0870f309cd6c659ea5925ef5a3d22e5203a375.zip"; sha256 = "9a1dfff8872c579bf8bd9e605d4d99579e3a5784fca4053e1463e03510bbb98d"; urls = [ "https://api.github.com/repos/php-http/message-factory/zipball/a478cb11f66a6ac48d8954216cfed9aa06a501a1" ]; }
    { name = "psr_container-2.0.2.0"; filename = "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip"; sha256 = "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"; urls = [ "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963" ]; }
    { name = "psr_http-factory-1.0.1.0"; filename = "psr/http-factory/554dafa2f4680a78fa693cedcbe62bc6873809db.zip"; sha256 = "baedc0aa21248f8a0316a8b78c98754cf7c4b3fe8ab7a4da5ad0adc22eb6cb46"; urls = [ "https://api.github.com/repos/php-fig/http-factory/zipball/12ac7fcd07e5b077433f5f2bee95b3a771bf61be" ]; }
    { name = "psr_http-message-1.0.1.0"; filename = "psr/http-message/cc1d4e9ee13f2053b80c08976256789bf3be5256.zip"; sha256 = "8538467ca2665fe15574f4d2506871823f71fd24b9a9284aae2ba90d8f69ada4"; urls = [ "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363" ]; }
    { name = "psr_http-server-handler-1.0.1.0"; filename = "psr/http-server-handler/3e4398b37dd092bb1f62653d8810cab13c6028a2.zip"; sha256 = "9df8319abcf5e0236cc26e70819295798ae27ac57881fa41a33ac74e930cdf69"; urls = [ "https://api.github.com/repos/php-fig/http-server-handler/zipball/aff2f80e33b7f026ec96bb42f63242dc50ffcae7" ]; }
    { name = "psr_http-server-middleware-1.0.1.0"; filename = "psr/http-server-middleware/191b7f9e08d6b4893ea296f41c5385246a7fe3c5.zip"; sha256 = "f2013d5ce5c972db00801a4232e202fecd1d679974e25e9565dd2e0f85ec22e5"; urls = [ "https://api.github.com/repos/php-fig/http-server-middleware/zipball/2296f45510945530b9dceb8bcedb5cb84d40c5f5" ]; }
    { name = "psr_log-3.0.0.0"; filename = "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip"; sha256 = "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"; urls = [ "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001" ]; }
    { name = "symfony_console-6.1.4.0"; filename = "symfony/console/261900ca17f4a8893a7192cbfaa2e77081f1b305.zip"; sha256 = "6c9b20d1022f9ce6ba2daacd5a5c2c370cab4c6fb8187577665ab236cadf4734"; urls = [ "https://api.github.com/repos/symfony/console/zipball/7fccea8728aa2d431a6725b02b3ce759049fc84d" ]; }
    { name = "symfony_deprecation-contracts-3.1.1.0"; filename = "symfony/deprecation-contracts/dca2a27a37c80362e0b71ac9d045563c036fab83.zip"; sha256 = "a0120eea2146c29e44bf2e62b0326e951b508483f202f4e3535ec5e546dcfea1"; urls = [ "https://api.github.com/repos/symfony/deprecation-contracts/zipball/07f1b9cc2ffee6aaafcf4b710fbc38ff736bd918" ]; }
    { name = "symfony_polyfill-ctype-1.26.0.0"; filename = "symfony/polyfill-ctype/81dd04d88f1f9151715ddca6520173db239a8db9.zip"; sha256 = "6ae1955d8f7b5d18967a3f5bcb910cd664fc7da9d4ff3bfab7a9cb8b632f43a0"; urls = [ "https://api.github.com/repos/symfony/polyfill-ctype/zipball/6fd1b9a79f6e3cf65f9e679b23af304cd9e010d4" ]; }
    { name = "symfony_polyfill-intl-grapheme-1.26.0.0"; filename = "symfony/polyfill-intl-grapheme/d3a40f7624005537657f7b2390e399d9892be5cd.zip"; sha256 = "8f85460e03a1ec08d2c3d4faf9beb397e00d91ca2a06b3422a19d634a04c2684"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/433d05519ce6990bf3530fba6957499d327395c2" ]; }
    { name = "symfony_polyfill-intl-normalizer-1.26.0.0"; filename = "symfony/polyfill-intl-normalizer/4eef99810616b77605bb089d8dfd1f79ebf9b434.zip"; sha256 = "5c0817d99bfb7c0399f67c5e447a06d73a8c38961c41a97d8ae412fc559e8cb3"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/219aa369ceff116e673852dce47c3a41794c14bd" ]; }
    { name = "symfony_polyfill-mbstring-1.26.0.0"; filename = "symfony/polyfill-mbstring/54165ccd6617b49a7c13c7ce6515c2f36a6ecec4.zip"; sha256 = "081b68a5b03baf94d4b0fe096b497c9a26e7155d45f64837ca8f2616524f4878"; urls = [ "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/9344f9cb97f3b19424af1a21a3b0e75b0a7d8d7e" ]; }
    { name = "symfony_service-contracts-3.1.1.0"; filename = "symfony/service-contracts/81a30ff05900d7fc2466c0df3cf18fe0839f9d1d.zip"; sha256 = "5e684049f405368d934ec578e7079f31937415a78eac5638c590b707027624af"; urls = [ "https://api.github.com/repos/symfony/service-contracts/zipball/925e713fe8fcacf6bc05e936edd8dd5441a21239" ]; }
    { name = "symfony_string-6.1.4.0"; filename = "symfony/string/691403c6758c38edb083c3e669e7fa9a6d89506e.zip"; sha256 = "2dd682c82acdbedd8a917e90390a2e7749657998d015bb6cc0cca3537d0634c4"; urls = [ "https://api.github.com/repos/symfony/string/zipball/290972cad7b364e3befaa74ba0ec729800fb161c" ]; }
    { name = "tuupola_base58-2.1.0.0"; filename = "tuupola/base58/0779200f0c82fa796210cb528750df591685aada.zip"; sha256 = "65d721514fb4bc82f130b3654321bace09574c3c7a51358200e698e812ac3153"; urls = [ "https://api.github.com/repos/tuupola/base58/zipball/4cd1a3972679946e87c0746f59ff8f0760240b4c" ]; }
    { name = "tuupola_base62-2.1.0.0"; filename = "tuupola/base62/e044fecd8fbee6caf3d021964a6c9f2bae9e99f0.zip"; sha256 = "8e3fa8b815155c73d3bdd00f43bcb838ee35685bb3472e891d6b9c3ded2fe966"; urls = [ "https://api.github.com/repos/tuupola/base62/zipball/7406145a9cf8c567cd35ad7358d1b24828cbcfdb" ]; }
    { name = "doctrine_instantiator-1.4.1.0"; filename = "doctrine/instantiator/b6977602bc07407dd2e3c71223021731d80df6d6.zip"; sha256 = "e74aae2efad779dc6044b0b5d3ac4cf56eb41a511549ed35e6046cb4d6e0d7d4"; urls = [ "https://api.github.com/repos/doctrine/instantiator/zipball/10dcfce151b967d20fde1b34ae6640712c3891bc" ]; }
    { name = "myclabs_deep-copy-1.11.0.0"; filename = "myclabs/deep-copy/8a47e905abc875fa8049c320097a46a9c305b50b.zip"; sha256 = "3c357c9554caa4d6d71117ce8cfb7db23c1ac64eb28a1e659988cbcf201ba984"; urls = [ "https://api.github.com/repos/myclabs/DeepCopy/zipball/14daed4296fae74d9e3201d2c4925d1acb7aa614" ]; }
    { name = "nikic_php-parser-4.14.0.0"; filename = "nikic/php-parser/8eaff525be82522f19fba8ffb0e035e0241cc815.zip"; sha256 = "e2f044cff0aa5fcd74589fa954680f2d4f3921c2854a8e8d2988f4c6923c49fa"; urls = [ "https://api.github.com/repos/nikic/PHP-Parser/zipball/34bea19b6e03d8153165d8f30bba4c3be86184c1" ]; }
    { name = "phar-io_manifest-2.0.3.0"; filename = "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip"; sha256 = "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"; urls = [ "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53" ]; }
    { name = "phar-io_version-3.2.1.0"; filename = "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip"; sha256 = "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"; urls = [ "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74" ]; }
    { name = "phpunit_php-code-coverage-9.2.17.0"; filename = "phpunit/php-code-coverage/68e2904371578d7cc1c1938fab1bf3a3928f4411.zip"; sha256 = "41da9c4c409c06e9b093ca3bdfc4a835042a61f286af622eeffaf1eb01afe4da"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/aa94dc41e8661fe90c7316849907cba3007b10d8" ]; }
    { name = "phpunit_php-file-iterator-3.0.6.0"; filename = "phpunit/php-file-iterator/4fd4ef934d9b090aff1c14e5987f251c5d6b2d0c.zip"; sha256 = "d9b2fe0929a3a844490dd9d32dbbd09a19713e3356e0199b26bc0c181c6a0790"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf" ]; }
    { name = "phpunit_php-invoker-3.1.1.0"; filename = "phpunit/php-invoker/18d90380b8ff6f566265ca070b4bcfe4c4bbd34c.zip"; sha256 = "d091fc2206ce86ff8664068b04952c8d8ff6dc12b7d864c1a8bf92c4adb416ef"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-invoker/zipball/5a10147d0aaf65b58940a0b72f71c9ac0423cc67" ]; }
    { name = "phpunit_php-text-template-2.0.4.0"; filename = "phpunit/php-text-template/b8d58f7d3789d6fd84cb6a82ebcb5776ab609787.zip"; sha256 = "98a2b504e34e4b99e433f6d738b877d5847ea9b2800f7d8534f147eebf3fc839"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28" ]; }
    { name = "phpunit_php-timer-5.0.3.0"; filename = "phpunit/php-timer/b71ded866a460bbdb922b5eb818f4ed163f38f0c.zip"; sha256 = "cacc8ec54d593bfaa1627bc67e110b0ef9d2f1d2ae98007d8b2bcc4fbc3f2f3c"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2" ]; }
    { name = "phpunit_phpunit-9.5.24.0"; filename = "phpunit/phpunit/d9528c0b6e7a2b211bfab6d63b56ea15bb69f102.zip"; sha256 = "4b5beb66c32f440b9c11daf578afa55366eac51bc2bb7cefcba290fa58be5537"; urls = [ "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/d0aa6097bef9fd42458a9b3c49da32c6ce6129c5" ]; }
    { name = "roave_security-advisories-dev-master"; filename = "roave/security-advisories/0a9c1111924752085510605b1abb307740a88bf0.zip"; sha256 = "70d8e34c9e396b09482ffbcf680c8da34c066de26c3b42a534e9e0851eb1a79c"; urls = [ "https://api.github.com/repos/Roave/SecurityAdvisories/zipball/6d260392fad173d6ee6e3a93c875d9327db1109b" ]; }
    { name = "sebastian_cli-parser-1.0.1.0"; filename = "sebastian/cli-parser/f4b297cc8d9ba3ba47f6d1c84b9d69bac882a7b1.zip"; sha256 = "6740017ab612481526b458876d8a9aba23326099ca0e0cb7263dcd1470fb981c"; urls = [ "https://api.github.com/repos/sebastianbergmann/cli-parser/zipball/442e7c7e687e42adc03470c7b668bc4b2402c0b2" ]; }
    { name = "sebastian_code-unit-1.0.8.0"; filename = "sebastian/code-unit/2175508c3a7c4f57c236668e95692cb4f230ef7e.zip"; sha256 = "f51e89b8ecce2a310a2cef0d7e8256378540fe1da91daa7a25a5e50c0ae87413"; urls = [ "https://api.github.com/repos/sebastianbergmann/code-unit/zipball/1fc9f64c0927627ef78ba436c9b17d967e68e120" ]; }
    { name = "sebastian_code-unit-reverse-lookup-2.0.3.0"; filename = "sebastian/code-unit-reverse-lookup/68fb878dfd88a53caa52899dcad6f00ede9925b2.zip"; sha256 = "4a6a9beb03ba89c65df74e0200eef997aed640f362a94a224e61aa3ffe5f32c0"; urls = [ "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5" ]; }
    { name = "sebastian_comparator-4.0.6.0"; filename = "sebastian/comparator/a3f1223b57dac9c414046a660ab1a23f1f344f6e.zip"; sha256 = "90e934b7907a501f6e2687f69daea642f4a555216bc1c4edb0137451897b8bb4"; urls = [ "https://api.github.com/repos/sebastianbergmann/comparator/zipball/55f4261989e546dc112258c7a75935a81a7ce382" ]; }
    { name = "sebastian_complexity-2.0.2.0"; filename = "sebastian/complexity/76ac0bc95bb26576a1588ac4917fe13f3107573f.zip"; sha256 = "ce23bcd6c0fe24007e0ad6bf3cc17fa7beedf11dfdc6e46c84eb6b882cfa9ef8"; urls = [ "https://api.github.com/repos/sebastianbergmann/complexity/zipball/739b35e53379900cc9ac327b2147867b8b6efd88" ]; }
    { name = "sebastian_diff-4.0.4.0"; filename = "sebastian/diff/527dd851ed7cdbd6b86e440441567b594e489fde.zip"; sha256 = "b209732f1736f8eb065781ac87b69bc0d8a752f19df0813ed820dbc60cb5c724"; urls = [ "https://api.github.com/repos/sebastianbergmann/diff/zipball/3461e3fccc7cfdfc2720be910d3bd73c69be590d" ]; }
    { name = "sebastian_environment-5.1.4.0"; filename = "sebastian/environment/0b7f292f62f46ed49ae0d70b39bfa393b4211611.zip"; sha256 = "2119946edb20c6bde2b716a4c85a0ef2e6ec96abc365c50ffc0044986e551762"; urls = [ "https://api.github.com/repos/sebastianbergmann/environment/zipball/1b5dff7bb151a4db11d49d90e5408e4e938270f7" ]; }
    { name = "sebastian_exporter-4.0.4.0"; filename = "sebastian/exporter/320e9b1623d61cf21f487908a0e706c538f2c11d.zip"; sha256 = "1834e5f7d671902ac4352202ec5bd4e44bed0a9d99c2a0dd509adac3e508281c"; urls = [ "https://api.github.com/repos/sebastianbergmann/exporter/zipball/65e8b7db476c5dd267e65eea9cab77584d3cfff9" ]; }
    { name = "sebastian_global-state-5.0.5.0"; filename = "sebastian/global-state/1cf3bc48e84c37ec54b03a90443ac94230cef95b.zip"; sha256 = "e14d22f89153d22e02b21b305a34258e43992ef7ab3a2ac2517fc7b38a7259b3"; urls = [ "https://api.github.com/repos/sebastianbergmann/global-state/zipball/0ca8db5a5fc9c8646244e629625ac486fa286bf2" ]; }
    { name = "sebastian_lines-of-code-1.0.3.0"; filename = "sebastian/lines-of-code/c83c674fbb96cf1b9525472250a2ec5c8e7784d6.zip"; sha256 = "60ae97d500e9d96e826afb01b5789c511fdb7fe6304a7c325fcf84ca8a4e5e39"; urls = [ "https://api.github.com/repos/sebastianbergmann/lines-of-code/zipball/c1c2e997aa3146983ed888ad08b15470a2e22ecc" ]; }
    { name = "sebastian_object-enumerator-4.0.4.0"; filename = "sebastian/object-enumerator/da625947c9c4e28182677035866359692138e8aa.zip"; sha256 = "c132dcacda3e4e0967aeabf068fa83f3f492a351c34bcd8f5101227ec01f0585"; urls = [ "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/5c9eeac41b290a3712d88851518825ad78f45c71" ]; }
    { name = "sebastian_object-reflector-2.0.4.0"; filename = "sebastian/object-reflector/89595d8936651649889c35a91221207e12331fda.zip"; sha256 = "4f673297cc7e85c41c8658c202e01ead4adae48d6c870ec070941bcfb50bb53c"; urls = [ "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/b4f479ebdbf63ac605d183ece17d8d7fe49c15c7" ]; }
    { name = "sebastian_recursion-context-4.0.4.0"; filename = "sebastian/recursion-context/6458bc6eb2e2dab0f0e7550c596001dd26243950.zip"; sha256 = "fe429b1e155104d66e0a930e44853d0a3daf790965f0a57712c3609e678813cc"; urls = [ "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/cd9d8cf3c5804de4341c283ed787f099f5506172" ]; }
    { name = "sebastian_resource-operations-3.0.3.0"; filename = "sebastian/resource-operations/c70bff160e611fd40d5d68d1f06d580b9496fb3a.zip"; sha256 = "d92f4b5b50d5e264d3b00ab31a3b80c0718f2689a1f3f23d101ce67a6e46ba5c"; urls = [ "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8" ]; }
    { name = "sebastian_type-3.1.0.0"; filename = "sebastian/type/229d4d8ba641456234c84a120160c76268575038.zip"; sha256 = "4afe7cd4827f783c55e8184e0245a522a39e036dcb8574c5073990d4c6961ca0"; urls = [ "https://api.github.com/repos/sebastianbergmann/type/zipball/fb44e1cc6e557418387ad815780360057e40753e" ]; }
    { name = "sebastian_version-3.0.2.0"; filename = "sebastian/version/85e202da271e8389420827021d6c4f00bdd90951.zip"; sha256 = "e1c5424e05207360f511745290144dcad1df69f1789fd97eb0d1819a145f47af"; urls = [ "https://api.github.com/repos/sebastianbergmann/version/zipball/c6c1022351a901512170118436c764e473f6de8c" ]; }
    { name = "stephank_composer-plugin-nixify-1.1.0.0"; filename = "stephank/composer-plugin-nixify/6b00aedf28221acbb64a87222a0eb819404901f2.zip"; sha256 = "ac7cc480698f8717fb9fce4077b81303d37fe6ab2b89c8547cd7f9451598ee1e"; urls = [ "https://api.github.com/repos/stephank/composer-plugin-nixify/zipball/d93c4348388d714d7d81b41e34ccb2ae9c2131c2" ]; }
    { name = "symplify_monorepo-builder-11.1.6.0"; filename = "symplify/monorepo-builder/487298ae589ffaeb990cc7a50b66b66b169b4c19.zip"; sha256 = "b0389244617695af0bc34608a2daee496e0f446e27268334f290e1ac3e1fee08"; urls = [ "https://api.github.com/repos/symplify/monorepo-builder/zipball/1e9d5d865759314334b2b34dca5d2fc39dd1051c" ]; }
    { name = "theseer_tokenizer-1.2.1.0"; filename = "theseer/tokenizer/9c419ba4ed9d43ff57a21270f44363ad0bed22f7.zip"; sha256 = "18d8c32441b19070ed7643321f5d3d5ee07217b991bee605cf64c979025044fd"; urls = [ "https://api.github.com/repos/theseer/tokenizer/zipball/34a41e998c2183e22995f158c581e7b5e755ab9e" ]; }
  ];
  localPackages = [
  ];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings (args: ''
      (
        cacheFile=${escapeShellArg args.filename}
        cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
        mkdir -p "$(dirname "$cacheFilePath")"
        cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
      )
    '') cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings (args: ''
      sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
    '') localPackages
  );

in stdenv.mkDerivation {
  name = "meteia_meteia";
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
