# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib, php, phpPackages, unzip, stdenv, runCommandLocal, writeText, fetchurl

# Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let

  composerPath = phpPackages.composer.src;
  cacheEntries = [
    { name = "aura_sql-dev-psr-log-v3"; filename = "aura/sql/dd6a88b233bb7f87bb68c86cf3507c41806887fa.zip"; sha256 = "95fdfefba857723202f6b318d968af3216f5086573dceaf02a420285747f2406"; urls = [ "https://api.github.com/repos/jasonrm/Aura.Sql/zipball/c58ba7efeba12a4621facfa38cde30b8afcbd1f3" ]; }
    { name = "guzzlehttp_guzzle-7.5.0.0"; filename = "guzzlehttp/guzzle/01743f83cc505a0464ba7a1a4507444403a079c7.zip"; sha256 = "37ddb40b16d8df64994dd3cdd41011109fe34ff02c4c00252adda9093212c833"; urls = [ "https://api.github.com/repos/guzzle/guzzle/zipball/b50a2a1251152e43f6a37f0fa053e730a67d25ba" ]; }
    { name = "guzzlehttp_promises-1.5.2.0"; filename = "guzzlehttp/promises/691eab84bb1e9e2a0b452c7fed0eb1f67862a516.zip"; sha256 = "e8efd4c91f3b0302c055cfcbeba9d869a93db8aad2b7f3242e257555fc616aef"; urls = [ "https://api.github.com/repos/guzzle/promises/zipball/b94b2807d85443f9719887892882d0329d1e2598" ]; }
    { name = "guzzlehttp_psr7-2.4.3.0"; filename = "guzzlehttp/psr7/f029e31b3f0f082aed4213b0cf7953278f2018b2.zip"; sha256 = "8fa79e2da503be7c4b1a91aeafa1bf303b7f3d48fca7dd8bba8efffa7b815b25"; urls = [ "https://api.github.com/repos/guzzle/psr7/zipball/67c26b443f348a51926030c83481b85718457d3d" ]; }
    { name = "laminas_laminas-diactoros-2.22.0.0"; filename = "laminas/laminas-diactoros/3855f417314b1e566c8e34e6ca07420ce002dce5.zip"; sha256 = "ef5ebe58d834211a523f78a585e1e42ffa23794e27834dc1da4c06e7ba95b0d2"; urls = [ "https://api.github.com/repos/laminas/laminas-diactoros/zipball/df8c7f9e11d854269f4aa7c06ffa38caa42e4405" ]; }
    { name = "league_mime-type-detection-1.11.0.0"; filename = "league/mime-type-detection/f9602cfc5f45723d4f590e49e3683471bec330cb.zip"; sha256 = "dfed2ddf02aee15b220396813b02e48e0d662cd772233f26dbe333d3f0b6c3a8"; urls = [ "https://api.github.com/repos/thephpleague/mime-type-detection/zipball/ff6248ea87a9f116e78edd6002e39e5128a0d4dd" ]; }
    { name = "nyholm_psr7-1.5.1.0"; filename = "nyholm/psr7/5d6f09262bdbe7949bc2811cc73627ff51f389c1.zip"; sha256 = "9db56258c34bfd5a355a8196242a85f371252cbf2f7caf7f60b3a187032d1171"; urls = [ "https://api.github.com/repos/Nyholm/psr7/zipball/f734364e38a876a23be4d906a2a089e1315be18a" ]; }
    { name = "nyholm_psr7-server-1.0.2.0"; filename = "nyholm/psr7-server/fd3271e24f437b2fd91b74592dcdb152667fd079.zip"; sha256 = "206e92ebfcb8635b8ad6f460bdf5584b9dd7a139e18dd549b78c7d9e1582e600"; urls = [ "https://api.github.com/repos/Nyholm/psr7-server/zipball/b846a689844cef114e8079d8c80f0afd96745ae3" ]; }
    { name = "php-http_message-factory-1.0.2.0"; filename = "php-http/message-factory/3a0870f309cd6c659ea5925ef5a3d22e5203a375.zip"; sha256 = "9a1dfff8872c579bf8bd9e605d4d99579e3a5784fca4053e1463e03510bbb98d"; urls = [ "https://api.github.com/repos/php-http/message-factory/zipball/a478cb11f66a6ac48d8954216cfed9aa06a501a1" ]; }
    { name = "psr_container-2.0.2.0"; filename = "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip"; sha256 = "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"; urls = [ "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963" ]; }
    { name = "psr_http-client-1.0.1.0"; filename = "psr/http-client/9ef0ac1a0bb8280477e24c9232fac374ed3024ac.zip"; sha256 = "fb98c497fe0d21d34c55622f687766e22198037a3c073fec44394439948bb332"; urls = [ "https://api.github.com/repos/php-fig/http-client/zipball/2dfb5f6c5eff0e91e20e913f8c5452ed95b86621" ]; }
    { name = "psr_http-factory-1.0.1.0"; filename = "psr/http-factory/554dafa2f4680a78fa693cedcbe62bc6873809db.zip"; sha256 = "baedc0aa21248f8a0316a8b78c98754cf7c4b3fe8ab7a4da5ad0adc22eb6cb46"; urls = [ "https://api.github.com/repos/php-fig/http-factory/zipball/12ac7fcd07e5b077433f5f2bee95b3a771bf61be" ]; }
    { name = "psr_http-message-1.0.1.0"; filename = "psr/http-message/cc1d4e9ee13f2053b80c08976256789bf3be5256.zip"; sha256 = "8538467ca2665fe15574f4d2506871823f71fd24b9a9284aae2ba90d8f69ada4"; urls = [ "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363" ]; }
    { name = "psr_http-server-handler-1.0.1.0"; filename = "psr/http-server-handler/3e4398b37dd092bb1f62653d8810cab13c6028a2.zip"; sha256 = "9df8319abcf5e0236cc26e70819295798ae27ac57881fa41a33ac74e930cdf69"; urls = [ "https://api.github.com/repos/php-fig/http-server-handler/zipball/aff2f80e33b7f026ec96bb42f63242dc50ffcae7" ]; }
    { name = "psr_http-server-middleware-1.0.1.0"; filename = "psr/http-server-middleware/191b7f9e08d6b4893ea296f41c5385246a7fe3c5.zip"; sha256 = "f2013d5ce5c972db00801a4232e202fecd1d679974e25e9565dd2e0f85ec22e5"; urls = [ "https://api.github.com/repos/php-fig/http-server-middleware/zipball/2296f45510945530b9dceb8bcedb5cb84d40c5f5" ]; }
    { name = "psr_log-3.0.0.0"; filename = "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip"; sha256 = "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"; urls = [ "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001" ]; }
    { name = "ralouphie_getallheaders-3.0.3.0"; filename = "ralouphie/getallheaders/ddc5f4c7ab3d868f5060717336a0d93475d53175.zip"; sha256 = "ef0165da5690da666ab4cb88bb4cec0d50372e3e7c922532c5795a3567b367af"; urls = [ "https://api.github.com/repos/ralouphie/getallheaders/zipball/120b605dfeb996808c31b6477290a714d356e822" ]; }
    { name = "symfony_console-6.2.0.0"; filename = "symfony/console/6c0c054113435dd7b17cae3d1d42014bd24d9d1a.zip"; sha256 = "5b0cbdb47c56ab63ae490206149d8eee2a4ffaac709e5497e936aafbdae1505a"; urls = [ "https://api.github.com/repos/symfony/console/zipball/75d4749d9620a8fa21a2d2847800a84b5c4e7682" ]; }
    { name = "symfony_deprecation-contracts-3.1.1.0"; filename = "symfony/deprecation-contracts/dca2a27a37c80362e0b71ac9d045563c036fab83.zip"; sha256 = "a0120eea2146c29e44bf2e62b0326e951b508483f202f4e3535ec5e546dcfea1"; urls = [ "https://api.github.com/repos/symfony/deprecation-contracts/zipball/07f1b9cc2ffee6aaafcf4b710fbc38ff736bd918" ]; }
    { name = "symfony_polyfill-ctype-1.27.0.0"; filename = "symfony/polyfill-ctype/04e84c03a82a82c09eaa688b17b523570f9d14d2.zip"; sha256 = "66f212bc73088271dbbec1f3b1c3ba21171e4c5ab38676c4d151441f3e38db6f"; urls = [ "https://api.github.com/repos/symfony/polyfill-ctype/zipball/5bbc823adecdae860bb64756d639ecfec17b050a" ]; }
    { name = "symfony_polyfill-intl-grapheme-1.27.0.0"; filename = "symfony/polyfill-intl-grapheme/3e0defb9f075160deb0ea7188610275ee40a9b00.zip"; sha256 = "11c409622d2321bfdd2fd1efdbdeaaba95da5211256f6cfdb4e003d7bd7eda45"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/511a08c03c1960e08a883f4cffcacd219b758354" ]; }
    { name = "symfony_polyfill-intl-normalizer-1.27.0.0"; filename = "symfony/polyfill-intl-normalizer/3282f96073427a186419bc5ae65aa6726d0f143b.zip"; sha256 = "22bf30d7b50aabe1846e3ffbc03011903e05f4208d3bb49b373c4e5fe09500b5"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/19bd1e4fcd5b91116f14d8533c57831ed00571b6" ]; }
    { name = "symfony_polyfill-mbstring-1.27.0.0"; filename = "symfony/polyfill-mbstring/7061da8bfb2a98acfbdcaf076c3ba5f167d856cc.zip"; sha256 = "b112101451a1f76a0cb4edd6595a5733059fd2f7a4cd4d36052526602e26a8fa"; urls = [ "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/8ad114f6b39e2c98a8b0e3bd907732c207c2b534" ]; }
    { name = "symfony_service-contracts-3.1.1.0"; filename = "symfony/service-contracts/81a30ff05900d7fc2466c0df3cf18fe0839f9d1d.zip"; sha256 = "5e684049f405368d934ec578e7079f31937415a78eac5638c590b707027624af"; urls = [ "https://api.github.com/repos/symfony/service-contracts/zipball/925e713fe8fcacf6bc05e936edd8dd5441a21239" ]; }
    { name = "symfony_string-6.2.0.0"; filename = "symfony/string/3b9cea7bc5293ff44a5a896b9f82ade092f7dd47.zip"; sha256 = "1dca27eb6e4c9059fdb7cc3f9824bb9766ea0e1e28ce1fb9c150fba67f4c2ea8"; urls = [ "https://api.github.com/repos/symfony/string/zipball/145702685e0d12f81d755c71127bfff7582fdd36" ]; }
    { name = "tuupola_base62-2.1.0.0"; filename = "tuupola/base62/e044fecd8fbee6caf3d021964a6c9f2bae9e99f0.zip"; sha256 = "8e3fa8b815155c73d3bdd00f43bcb838ee35685bb3472e891d6b9c3ded2fe966"; urls = [ "https://api.github.com/repos/tuupola/base62/zipball/7406145a9cf8c567cd35ad7358d1b24828cbcfdb" ]; }
    { name = "webonyx_graphql-php-14.11.8.0"; filename = "webonyx/graphql-php/cbda84aaeecd605fe8f7ab801ebd218b50f0cc81.zip"; sha256 = "6ff6f43d280c2bceec39559eaf35ccd1ad950c7ac4a907bb6194ede2169a17ef"; urls = [ "https://api.github.com/repos/webonyx/graphql-php/zipball/04a48693acd785330eefd3b0e4fa67df8dfee7c3" ]; }
    { name = "doctrine_instantiator-1.4.1.0"; filename = "doctrine/instantiator/b6977602bc07407dd2e3c71223021731d80df6d6.zip"; sha256 = "e74aae2efad779dc6044b0b5d3ac4cf56eb41a511549ed35e6046cb4d6e0d7d4"; urls = [ "https://api.github.com/repos/doctrine/instantiator/zipball/10dcfce151b967d20fde1b34ae6640712c3891bc" ]; }
    { name = "myclabs_deep-copy-1.11.0.0"; filename = "myclabs/deep-copy/8a47e905abc875fa8049c320097a46a9c305b50b.zip"; sha256 = "3c357c9554caa4d6d71117ce8cfb7db23c1ac64eb28a1e659988cbcf201ba984"; urls = [ "https://api.github.com/repos/myclabs/DeepCopy/zipball/14daed4296fae74d9e3201d2c4925d1acb7aa614" ]; }
    { name = "nikic_php-parser-4.15.2.0"; filename = "nikic/php-parser/e236b4c6515233fbea34d00815dd48192bfd54f1.zip"; sha256 = "b543992555ebe12789282ff5ae2037eff819ec5246b5d2f5dec1072f8b485c53"; urls = [ "https://api.github.com/repos/nikic/PHP-Parser/zipball/f59bbe44bf7d96f24f3e2b4ddc21cd52c1d2adbc" ]; }
    { name = "phar-io_manifest-2.0.3.0"; filename = "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip"; sha256 = "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"; urls = [ "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53" ]; }
    { name = "phar-io_version-3.2.1.0"; filename = "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip"; sha256 = "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"; urls = [ "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74" ]; }
    { name = "phpunit_php-code-coverage-9.2.19.0"; filename = "phpunit/php-code-coverage/e3a940c455470c15124bd416a2f2f93dc64359cc.zip"; sha256 = "79e9160bb48bfcbbf41af90ff624b7abe926bb9f4240cfab46721fe6d260ebd0"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/c77b56b63e3d2031bd8997fcec43c1925ae46559" ]; }
    { name = "phpunit_php-file-iterator-3.0.6.0"; filename = "phpunit/php-file-iterator/4fd4ef934d9b090aff1c14e5987f251c5d6b2d0c.zip"; sha256 = "d9b2fe0929a3a844490dd9d32dbbd09a19713e3356e0199b26bc0c181c6a0790"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf" ]; }
    { name = "phpunit_php-invoker-3.1.1.0"; filename = "phpunit/php-invoker/18d90380b8ff6f566265ca070b4bcfe4c4bbd34c.zip"; sha256 = "d091fc2206ce86ff8664068b04952c8d8ff6dc12b7d864c1a8bf92c4adb416ef"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-invoker/zipball/5a10147d0aaf65b58940a0b72f71c9ac0423cc67" ]; }
    { name = "phpunit_php-text-template-2.0.4.0"; filename = "phpunit/php-text-template/b8d58f7d3789d6fd84cb6a82ebcb5776ab609787.zip"; sha256 = "98a2b504e34e4b99e433f6d738b877d5847ea9b2800f7d8534f147eebf3fc839"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28" ]; }
    { name = "phpunit_php-timer-5.0.3.0"; filename = "phpunit/php-timer/b71ded866a460bbdb922b5eb818f4ed163f38f0c.zip"; sha256 = "cacc8ec54d593bfaa1627bc67e110b0ef9d2f1d2ae98007d8b2bcc4fbc3f2f3c"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2" ]; }
    { name = "phpunit_phpunit-9.5.26.0"; filename = "phpunit/phpunit/04426dd761d9708a3d3321a8583025b06bf09ce3.zip"; sha256 = "0f1abdfd7b4fb2ddd54ed65fa168f7fdf451ef58d7615c0bdb256e5dafd8544c"; urls = [ "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/851867efcbb6a1b992ec515c71cdcf20d895e9d2" ]; }
    { name = "roave_security-advisories-dev-master"; filename = "roave/security-advisories/2075684ad362b6cade90a588ea1685ab67dc492d.zip"; sha256 = "9da06d4531bad546f8d3c3572aa96ae97830fb64d90027d8ccc4a9cd68328f4b"; urls = [ "https://api.github.com/repos/Roave/SecurityAdvisories/zipball/891ecbb72eac808c80fb97f2cce67824e94e5652" ]; }
    { name = "sebastian_cli-parser-1.0.1.0"; filename = "sebastian/cli-parser/f4b297cc8d9ba3ba47f6d1c84b9d69bac882a7b1.zip"; sha256 = "6740017ab612481526b458876d8a9aba23326099ca0e0cb7263dcd1470fb981c"; urls = [ "https://api.github.com/repos/sebastianbergmann/cli-parser/zipball/442e7c7e687e42adc03470c7b668bc4b2402c0b2" ]; }
    { name = "sebastian_code-unit-1.0.8.0"; filename = "sebastian/code-unit/2175508c3a7c4f57c236668e95692cb4f230ef7e.zip"; sha256 = "f51e89b8ecce2a310a2cef0d7e8256378540fe1da91daa7a25a5e50c0ae87413"; urls = [ "https://api.github.com/repos/sebastianbergmann/code-unit/zipball/1fc9f64c0927627ef78ba436c9b17d967e68e120" ]; }
    { name = "sebastian_code-unit-reverse-lookup-2.0.3.0"; filename = "sebastian/code-unit-reverse-lookup/68fb878dfd88a53caa52899dcad6f00ede9925b2.zip"; sha256 = "4a6a9beb03ba89c65df74e0200eef997aed640f362a94a224e61aa3ffe5f32c0"; urls = [ "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5" ]; }
    { name = "sebastian_comparator-4.0.8.0"; filename = "sebastian/comparator/6a8576886b5e1cfd55783584d8a948ab21adc37c.zip"; sha256 = "7ca0bc15be7811ff9964e059889466bab579a93f7ed34cd02e58f0aef85c1155"; urls = [ "https://api.github.com/repos/sebastianbergmann/comparator/zipball/fa0f136dd2334583309d32b62544682ee972b51a" ]; }
    { name = "sebastian_complexity-2.0.2.0"; filename = "sebastian/complexity/76ac0bc95bb26576a1588ac4917fe13f3107573f.zip"; sha256 = "ce23bcd6c0fe24007e0ad6bf3cc17fa7beedf11dfdc6e46c84eb6b882cfa9ef8"; urls = [ "https://api.github.com/repos/sebastianbergmann/complexity/zipball/739b35e53379900cc9ac327b2147867b8b6efd88" ]; }
    { name = "sebastian_diff-4.0.4.0"; filename = "sebastian/diff/527dd851ed7cdbd6b86e440441567b594e489fde.zip"; sha256 = "b209732f1736f8eb065781ac87b69bc0d8a752f19df0813ed820dbc60cb5c724"; urls = [ "https://api.github.com/repos/sebastianbergmann/diff/zipball/3461e3fccc7cfdfc2720be910d3bd73c69be590d" ]; }
    { name = "sebastian_environment-5.1.4.0"; filename = "sebastian/environment/0b7f292f62f46ed49ae0d70b39bfa393b4211611.zip"; sha256 = "2119946edb20c6bde2b716a4c85a0ef2e6ec96abc365c50ffc0044986e551762"; urls = [ "https://api.github.com/repos/sebastianbergmann/environment/zipball/1b5dff7bb151a4db11d49d90e5408e4e938270f7" ]; }
    { name = "sebastian_exporter-4.0.5.0"; filename = "sebastian/exporter/d097047a341fb0e411c70e540a62a9ca3af9479c.zip"; sha256 = "d290d6d4c1ed86927a833cc9cceb9fefb4b55d6cda7774e38b43f28c3692dea8"; urls = [ "https://api.github.com/repos/sebastianbergmann/exporter/zipball/ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d" ]; }
    { name = "sebastian_global-state-5.0.5.0"; filename = "sebastian/global-state/1cf3bc48e84c37ec54b03a90443ac94230cef95b.zip"; sha256 = "e14d22f89153d22e02b21b305a34258e43992ef7ab3a2ac2517fc7b38a7259b3"; urls = [ "https://api.github.com/repos/sebastianbergmann/global-state/zipball/0ca8db5a5fc9c8646244e629625ac486fa286bf2" ]; }
    { name = "sebastian_lines-of-code-1.0.3.0"; filename = "sebastian/lines-of-code/c83c674fbb96cf1b9525472250a2ec5c8e7784d6.zip"; sha256 = "60ae97d500e9d96e826afb01b5789c511fdb7fe6304a7c325fcf84ca8a4e5e39"; urls = [ "https://api.github.com/repos/sebastianbergmann/lines-of-code/zipball/c1c2e997aa3146983ed888ad08b15470a2e22ecc" ]; }
    { name = "sebastian_object-enumerator-4.0.4.0"; filename = "sebastian/object-enumerator/da625947c9c4e28182677035866359692138e8aa.zip"; sha256 = "c132dcacda3e4e0967aeabf068fa83f3f492a351c34bcd8f5101227ec01f0585"; urls = [ "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/5c9eeac41b290a3712d88851518825ad78f45c71" ]; }
    { name = "sebastian_object-reflector-2.0.4.0"; filename = "sebastian/object-reflector/89595d8936651649889c35a91221207e12331fda.zip"; sha256 = "4f673297cc7e85c41c8658c202e01ead4adae48d6c870ec070941bcfb50bb53c"; urls = [ "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/b4f479ebdbf63ac605d183ece17d8d7fe49c15c7" ]; }
    { name = "sebastian_recursion-context-4.0.4.0"; filename = "sebastian/recursion-context/6458bc6eb2e2dab0f0e7550c596001dd26243950.zip"; sha256 = "fe429b1e155104d66e0a930e44853d0a3daf790965f0a57712c3609e678813cc"; urls = [ "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/cd9d8cf3c5804de4341c283ed787f099f5506172" ]; }
    { name = "sebastian_resource-operations-3.0.3.0"; filename = "sebastian/resource-operations/c70bff160e611fd40d5d68d1f06d580b9496fb3a.zip"; sha256 = "d92f4b5b50d5e264d3b00ab31a3b80c0718f2689a1f3f23d101ce67a6e46ba5c"; urls = [ "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8" ]; }
    { name = "sebastian_type-3.2.0.0"; filename = "sebastian/type/e4452efb1e3255d8306d160c941ba887a0c693b5.zip"; sha256 = "67748a67088f019de35d5a1213bb1f4e6954b6b20d62a234fef1cd615f4a95d2"; urls = [ "https://api.github.com/repos/sebastianbergmann/type/zipball/fb3fe09c5f0bae6bc27ef3ce933a1e0ed9464b6e" ]; }
    { name = "sebastian_version-3.0.2.0"; filename = "sebastian/version/85e202da271e8389420827021d6c4f00bdd90951.zip"; sha256 = "e1c5424e05207360f511745290144dcad1df69f1789fd97eb0d1819a145f47af"; urls = [ "https://api.github.com/repos/sebastianbergmann/version/zipball/c6c1022351a901512170118436c764e473f6de8c" ]; }
    { name = "stephank_composer-plugin-nixify-1.1.0.0"; filename = "stephank/composer-plugin-nixify/6b00aedf28221acbb64a87222a0eb819404901f2.zip"; sha256 = "ac7cc480698f8717fb9fce4077b81303d37fe6ab2b89c8547cd7f9451598ee1e"; urls = [ "https://api.github.com/repos/stephank/composer-plugin-nixify/zipball/d93c4348388d714d7d81b41e34ccb2ae9c2131c2" ]; }
    { name = "symplify_monorepo-builder-11.1.17.0"; filename = "symplify/monorepo-builder/6d5bd9aa3777d933507a6b556a4b87b4a3ff84e5.zip"; sha256 = "6ee860d6beba7ad79f974dd0844b7fb5315c1b5c67c33982c040a14fc9ad8492"; urls = [ "https://api.github.com/repos/symplify/monorepo-builder/zipball/a0549c6ba63a3ee35403f26e51563c82e4a599dc" ]; }
    { name = "theseer_tokenizer-1.2.1.0"; filename = "theseer/tokenizer/9c419ba4ed9d43ff57a21270f44363ad0bed22f7.zip"; sha256 = "18d8c32441b19070ed7643321f5d3d5ee07217b991bee605cf64c979025044fd"; urls = [ "https://api.github.com/repos/theseer/tokenizer/zipball/34a41e998c2183e22995f158c581e7b5e755ab9e" ]; }
  ];
  localPackages = [
  ];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings (args: ''
      (
        cacheFile=${escapeShellArg args.filename}
        cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
        mkdir -p "$(dirname "$cacheFilePath")"
        cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
      )
    '') cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings (args: ''
      sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
    '') localPackages
  );

in stdenv.mkDerivation {
  name = "meteia_meteia";
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
