<?php

declare(strict_types=1);

namespace Meteia\TypeScript;

use Meteia\Commands\Commands;
use Meteia\Events\Events;

final readonly class TypeScriptDeclarations
{
    public function __construct(
        private Commands $commands,
        private Events $events,
    ) {}

    public function content(): string
    {
        $commandClasses = $this->classes($this->commands);
        $eventClasses = $this->classes($this->events);

        return implode("\n", [
            '/* This file is generated by Meteia TypeScript:GenerateTypes. */',
            '/* Do not edit this file directly. */',
            '',
            $this->payloadDeclarations($commandClasses, 'Command'),
            $this->payloadDeclarations($eventClasses, 'Event'),
            $this->payloadMap('MeteiaCommandPayloads', $commandClasses, 'Command'),
            $this->payloadMap('MeteiaEventPayloads', $eventClasses, 'Event'),
            $this->messageUnion('MeteiaCommand', 'MeteiaCommandPayloads', 'command'),
            $this->messageUnion('MeteiaEvent', 'MeteiaEventPayloads', 'event'),
            'export type MeteiaMessage = MeteiaCommand | MeteiaEvent;',
            '',
        ]);
    }

    /**
     * @param iterable<class-string> $classes
     *
     * @return list<class-string>
     */
    private function classes(iterable $classes): array
    {
        $unique = [];
        foreach ($classes as $class) {
            $unique[$class] = $class;
        }
        ksort($unique);

        return array_values($unique);
    }

    /**
     * @param list<class-string> $classes
     */
    private function payloadDeclarations(array $classes, string $suffix): string
    {
        $declarations = [];
        foreach ($classes as $class) {
            $declarations[] = new ReflectedPayload($class, $suffix)->declaration();
        }

        return implode("\n", $declarations);
    }

    /**
     * @param list<class-string> $classes
     */
    private function payloadMap(string $name, array $classes, string $suffix): string
    {
        if ($classes === []) {
            return sprintf("export type %s = Readonly<Record<never, never>>;\n", $name);
        }

        $lines = [sprintf('export type %s = {', $name)];
        foreach ($classes as $class) {
            $payload = new ReflectedPayload($class, $suffix);
            $lines[] = sprintf('  readonly %s: %s;', $this->quoted($class), $payload->name());
        }
        $lines[] = "};\n";

        return implode("\n", $lines);
    }

    private function messageUnion(string $name, string $payloadMap, string $kind): string
    {
        return implode("\n", [
            sprintf('export type %s = {', $name),
            sprintf('  readonly [Type in keyof %s]: {', $payloadMap),
            sprintf('    readonly kind: %s;', $this->quoted($kind)),
            '    readonly type: Type;',
            sprintf('    readonly payload: %s[Type];', $payloadMap),
            '  }',
            sprintf('}[keyof %s];', $payloadMap),
            '',
        ]);
    }

    private function quoted(string $value): string
    {
        return json_encode($value, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);
    }
}
