<?php

declare(strict_types=1);

namespace Meteia\TypeScript;

use Meteia\Commands\Commands;
use Meteia\Events\Events;
use Meteia\TypeScript\Fixtures\CommandPayloads\ConfigureCookie;
use Meteia\TypeScript\Fixtures\CommandPayloads\RegisterStudent;
use Meteia\TypeScript\Fixtures\CommandPayloads\ScheduleLesson;
use Meteia\TypeScript\Fixtures\EventPayloads\StudentRegistered;
use Override;
use PHPUnit\Framework\TestCase;
use Traversable;

/**
 * @internal
 */
final class TypeScriptDeclarationsTest extends TestCase
{
    public function testGeneratesPayloadTypesForCommandsAndEvents(): void
    {
        $declarations = new TypeScriptDeclarations($this->commands(), $this->events());

        static::assertSame($this->expected(), $declarations->content());
    }

    private function commands(): Commands
    {
        return new class implements Commands {
            #[Override]
            public function getIterator(): Traversable
            {
                yield ScheduleLesson::class;
                yield RegisterStudent::class;
                yield ConfigureCookie::class;
            }
        };
    }

    private function events(): Events
    {
        return new class implements Events {
            #[Override]
            public function getIterator(): Traversable
            {
                yield StudentRegistered::class;
            }
        };
    }

    private function expected(): string
    {
        return <<<'TS'
/* This file is generated by Meteia TypeScript:GenerateTypes. */
/* Do not edit this file directly. */

export type Meteia_TypeScript_Fixtures_CommandPayloads_ConfigureCookieCommandPayload = {
  readonly sameSite: "Lax" | "None" | "Strict";
  readonly unsupportedPayload: unknown;
  readonly replyTo?: string | null;
};

export type Meteia_TypeScript_Fixtures_CommandPayloads_RegisterStudentCommandPayload = {
  readonly studentName: string;
  readonly age: number;
  readonly score: number;
  readonly active: boolean;
  readonly nickname: string | null;
};

export type Meteia_TypeScript_Fixtures_CommandPayloads_ScheduleLessonCommandPayload = {
  readonly tags: readonly unknown[] | { readonly [key: string]: unknown };
  readonly requestedAt: string;
  readonly causationId: string;
  readonly resource: string;
};

export type Meteia_TypeScript_Fixtures_EventPayloads_StudentRegisteredEventPayload = {
  readonly studentName: string;
};

export type MeteiaCommandPayloads = {
  readonly "Meteia\\TypeScript\\Fixtures\\CommandPayloads\\ConfigureCookie": Meteia_TypeScript_Fixtures_CommandPayloads_ConfigureCookieCommandPayload;
  readonly "Meteia\\TypeScript\\Fixtures\\CommandPayloads\\RegisterStudent": Meteia_TypeScript_Fixtures_CommandPayloads_RegisterStudentCommandPayload;
  readonly "Meteia\\TypeScript\\Fixtures\\CommandPayloads\\ScheduleLesson": Meteia_TypeScript_Fixtures_CommandPayloads_ScheduleLessonCommandPayload;
};

export type MeteiaEventPayloads = {
  readonly "Meteia\\TypeScript\\Fixtures\\EventPayloads\\StudentRegistered": Meteia_TypeScript_Fixtures_EventPayloads_StudentRegisteredEventPayload;
};

export type MeteiaCommand = {
  readonly [Type in keyof MeteiaCommandPayloads]: {
    readonly kind: "command";
    readonly type: Type;
    readonly payload: MeteiaCommandPayloads[Type];
  }
}[keyof MeteiaCommandPayloads];

export type MeteiaEvent = {
  readonly [Type in keyof MeteiaEventPayloads]: {
    readonly kind: "event";
    readonly type: Type;
    readonly payload: MeteiaEventPayloads[Type];
  }
}[keyof MeteiaEventPayloads];

export type MeteiaMessage = MeteiaCommand | MeteiaEvent;

TS;
    }
}
